### ISSUE TITLE
i18n improvements

### ISSUE THREAD

**Issue by Zodiac1978** [roytanck/rt-plugin-report#12]
I am not a native English speaker, but shouldn't this be "The" instead of "This"?
https://github.com/roytanck/rt-plugin-report/blob/develop/rt-plugin-report.php#L315

Any chance to get the plugin name here instead of just the slug?

**Comment by roytanck** [comment]
Good catch! Should definitely be "The". I'll see about getting the plugin name there too.

That being said, I'm also looking into using the WP_Error object returned by `plugins_api()` for better feedback (#11). If that object has a better error message, we could consider using that message as-is.
