### ISSUE TITLE
Update available is shown even if not

### ISSUE THREAD

**Issue by Zodiac1978** [roytanck/rt-plugin-report#17]
If the server is running a PHP version which is lower than the required version from the plugin or the required WP version higher than the actual WP version the plugin is showing "(Update available)" although it is not available for *this* server/WP environment.

It would be great to show a warning in this case `("Update available, but WP version x.y required")` or `("Update available, but PHP version x.y required")`.

**Comment by roytanck** [comment]
Good point. We should definitely still show the update, and try to nudge the user to update their environment. I'll see if the API gives me the info needed to do this.

**Comment by roytanck** [comment]
![Screenshot from 2020-02-10 15-50-37](https://user-images.githubusercontent.com/1642390/74160118-324ea980-4c1d-11ea-84db-f7468af73442.png)

It looks like the wp.org API allows me to get the required info. I do feel that the message can get a little long, especially if both the WP and PHP version are out of date.

@Zodiac1978 Any thoughts?

**Comment by Zodiac1978** [comment]
Maybe we could use a tooltip here (like in WooCommerce for the help text):
<img width="324" alt="Bildschirmfoto 2020-02-10 um 16 00 26" src="https://user-images.githubusercontent.com/870475/74161006-94f47500-4c1e-11ea-90ca-f628da15778a.png">

**Comment by roytanck** [comment]
I thought about that, but tooltips won't be exported to .xls. Maybe we can shorten the wording somewhat? "(1.2 available, requires WP 4.8 and PHP 7.2)" perhaps? I'm not bothered very much by the cell line-wrapping, but would like to avoid three lines of possible.

**Comment by Zodiac1978** [comment]
What about adding a new table row with `colspan="7"` and adding the complete text there? This could be exported in the XLS.

Shortening to the mentioned "(1.2 available, requires WP 4.8 and PHP 7.2)" is looking fine for me too.

**Comment by roytanck** [comment]
Added in https://github.com/roytanck/rt-plugin-report/commit/42763d124132783d93ba7e9daa0d2908a09f9517
