### ISSUE TITLE
Separate Plugin Name string from translatable strings

### ISSUE THREAD

**Issue by pedro-mendonca** [roytanck/rt-plugin-report#18]
This allows the translation of Plugin Report menu and page titles, without affecting plugin name, that shouldn't be translated.

Would you welcome a PR with this change?

**Comment by roytanck** [comment]
Absolutely. Might be a little while before a new version is released, but PR certainly welcome.

**Comment by pedro-mendonca** [comment]
@roytanck fixed in #19

**Comment by roytanck** [comment]
Thank you @pedro-mendonca . Would you like to be added to the contributors for this plugin? What is your wp.org username?

**Comment by pedro-mendonca** [comment]
Thanks, you can add me, no problem :)
My username is [@pedromendonca](https://profiles.wordpress.org/pedromendonca/)
