### ISSUE TITLE
Required WP version could be smaller

### ISSUE THREAD

**Issue by Zodiac1978** [roytanck/rt-plugin-report#3]
I check the plugin with https://wpseek.com/pluginfilecheck/ and the minimum required version seems to be 3.0.0 and not 5.0

https://github.com/roytanck/rt-plugin-report/blob/develop/README.txt#L4

The missing version info for `get_preferred_from_update_core` is 2.7.0, so it is below 3.0.0.

**Comment by roytanck** [comment]
Hmm... putting 3.0 there feels like a validation for people to keep running really old versions. I remember 3.0 vividly, and WP was very different back then.

**Comment by Zodiac1978** [comment]
> feels like a validation for people to keep running really old versions

I don't think this is the case. The official explanation is:

> Requires at least: The lowest WordPress version that the plugin will work on.

See: https://developer.wordpress.org/plugins/plugin-basics/header-requirements/#header-fields

So if you are using a function which is added in WP 4.7 for example this should be set to 4.7 to prevent this plugin to be added/updated to if you are using a lower version of WP.

**Comment by roytanck** [comment]
I lowered the required version to 4.6 in https://github.com/roytanck/rt-plugin-report/commit/0a7eda0ce699771f188db108e648c71545b6dcaf .
