### ISSUE TITLE
Disregard minor WP versions when comparing version numbers

### ISSUE THREAD

**Issue by roytanck** [roytanck/rt-plugin-report#35]
As reported here: https://wordpress.org/support/topic/minor-wp-versions/

The best approach would probably be to add a new get_wp_version_risk_classname() method that strips the third number before calling get_version_risk_classname(). Any columns dealing with WP serial numbers can then call that function to get the CSS class.

**Comment by roytanck** [comment]
For plugins hosted on wp.org, the API appears to return "5.5.1" as the "tested up to" value when the readme specifies "5.5". So it adds the point release automatically, which is why this issue only affects non-repo plugins.

**Comment by roytanck** [comment]
A potential fix is available here: https://github.com/roytanck/rt-plugin-report/commit/42847f48b4d39950550634bf9df4c8728f61e5d8

Waiting to hear back from the original reporter because I can't seem to find a plugin that exhibits this behavior. Non-repo plugins usually do not provide a "tested up to" value, and the wp-org repo adds the point release as described above.

**Comment by Zodiac1978** [comment]
This is fixed with version 1.8.1, or not? The you could close this issue. :)
