### ISSUE TITLE
Default sort order is different from WP's plugin page

### ISSUE THREAD

**Issue by roytanck** [roytanck/rt-plugin-report#38]
https://wordpress.org/support/topic/order-of-the-plugins-is-different-compared-to-the-plugin-list/

This probably has to do with WP sorting by slug (which would add "-" for spaces), whereas PR sorts strictly by the content of the table cells in the column.

@Zodiac1978 Since you implemented table sorting, perhaps you'd like to see whether this low hanging fruit?

**Comment by Zodiac1978** [comment]
WordPress is using the *translated* name for sorting (not the slug) with a custom comparison function based on `strcasecmp()`. 

We could try to solve this with adding a `data-sort` attribute on the name column (to solve the different sorting issues) which tries to get the same results as the WP solution. Maybe stripping spaces/dashes completely?

And we need to translate the plugin data, for example with this code borrowed from the internal [_get_plugin_data_markup_translate](https://developer.wordpress.org/reference/functions/_get_plugin_data_markup_translate/) function:

```
// Translate fields.
    if ( $translate ) {
        $textdomain = $plugin_data['TextDomain'];
        if ( $textdomain ) {
            if ( ! is_textdomain_loaded( $textdomain ) ) {
                if ( $plugin_data['DomainPath'] ) {
                    load_plugin_textdomain( $textdomain, false, dirname( $plugin_file ) . $plugin_data['DomainPath'] );
                } else {
                    load_plugin_textdomain( $textdomain, false, dirname( $plugin_file ) );
                }
            }
        } elseif ( 'hello.php' === basename( $plugin_file ) ) {
            $textdomain = 'default';
        }
        if ( $textdomain ) {
            foreach ( array( 'Name', 'PluginURI', 'Description', 'Author', 'AuthorURI', 'Version' ) as $field ) {
                // phpcs:ignore WordPress.WP.I18n.LowLevelTranslationFunction,WordPress.WP.I18n.NonSingularStringLiteralText,WordPress.WP.I18n.NonSingularStringLiteralDomain
                $plugin_data[ $field ] = translate( $plugin_data[ $field ], $textdomain );
            }
        }
    }
```

**Comment by roytanck** [comment]
How would this work for plugins where the translated name is significantly different (as in: starts with a different letter altogether)? We'd probably need to also display the translated name? Or are we already doing that?

**Comment by Zodiac1978** [comment]
In WordPress the translated plugin name is shown (if available). Unfortunately the solution in WP does not work correctly for German, as Umlauts, like ÜÖÄ are put to the end of the table. :/

![Bildschirmfoto 2021-03-29 um 15 03 06](https://user-images.githubusercontent.com/870475/112840636-dd2f5a80-909f-11eb-864b-ad028a6d8207.png)

In the `data-sort` attribute we additionally need to lowercase everything (for example).

My work in progress looks like this (replacing space with dash, lower case everything):

```
// Name.
if ( isset( $report['local_info']['PluginURI'] ) && ! empty( $report['local_info']['PluginURI'] ) ) {
	$html .= '<td data-sort="' . strtolower( str_replace( array( ' ' ), '-', $report['local_info']['Name'] ) ) . '"><a href="' . $report['local_info']['PluginURI'] . '"><strong>' . $report['local_info']['Name'] . '</strong></a></td>';
} else {
	$html .= '<td data-sort="' . strtolower( str_replace( array( ' ' ), '-', $report['local_info']['Name'] ) ) . '"><strong>' . $report['local_info']['Name'] . '</strong></td>';
}
```

But then I saw the main design flaw ... 🤦‍♂️

I forgot to add the default sorting. Adding `data-sort-default` to the name column for default sorting seems to fix it.

The translation still stands of course ...

**Comment by Zodiac1978** [comment]
Asked in the forums to confirm this. If this is the reason I will provide a PR soon.

**Comment by Zodiac1978** [comment]
The thread starter confirmed the fix by enabling the sorting. So we just have to add the default sorting column.

I will prepare the PR now. :)

**Comment by roytanck** [comment]
I think you mentioned that it's not recommended to translate plugin names? If so, I'd only attempt this if you feel like diving into it. The original issue has been fixed, and we've not seen any feedback about plugin names not being translated.

**Comment by Zodiac1978** [comment]
> I think you mentioned that it's not recommended to translate plugin names?

Yes, that's true. But sometimes plugin names are translated (for example Public Post Preview from Dominik Schilling in German). And maybe other locales have different policies about that. From the forums we know that nl_NL & nl_BE have this policy and de_DE has it too. I think the other de_xx locales follow the de_DE locale in that matter. I don't know about other locales.

At the moment Plugin Report does not show the translated name. 

I will try to do this with the approach from above. I already created a branch in my fork.

**Comment by Zodiac1978** [comment]
I experienced one additional edge case. WordPress does not distinguish between different types of dashes. But tablesort seems to be confused by dash vs. ndash vs. mdash. Not sure why this happens and how to solve this.

![Bildschirmfoto 2021-04-08 um 22 29 40](https://user-images.githubusercontent.com/870475/114159560-3449f080-9926-11eb-8cd6-e53a567bc730.png)

**Comment by Zodiac1978** [comment]
Nope, after examining this problem it is a bogus space. The space after the hyphen (or better n-dash in this case) wasn't a real space (0x0020) , but a non-breaking space (0xC2 0xA0).

//cc @webzunft

**Comment by Zodiac1978** [comment]
We could fix this on our end with on the plugin title/name:
`$regular_spaces = str_replace("\xc2\xa0", ' ', $original_string);`

@roytanck Do you think we should cover this edge case, or not?

**Comment by roytanck** [comment]
@Zodiac1978 I'd prefer a generic solution. Perhaps we can run the names though sanitize_title() and use the result in the table sort data attribute? Or use  [\s\S] to match any whitespace character, not just this particular edge case?

**Comment by Zodiac1978** [comment]
@roytanck The problem with `sanitize_title()` is, that it is using `remove_accents()` which would change the sorting for many locales (including German with its Umlauts "ÜÖÄüöä").

But using `\s` should work:
`$new_str = preg_replace("/\s+/u", " ", $str);`
From: https://stackoverflow.com/questions/40264465/how-to-correctly-replace-multiple-white-spaces-with-a-single-white-space-in-php/40264711#40264711
