### ISSUE TITLE
Text domain issues

### ISSUE THREAD

**Issue by Zodiac1978** [roytanck/rt-plugin-report#4]
There are some problems with the text domain and language file loading.

In the plugin header the text domain is "plugin-report":
https://github.com/roytanck/rt-plugin-report/blob/develop/rt-plugin-report.php#L10

But the function is using "rt-plugin-report":
https://github.com/roytanck/rt-plugin-report/blob/develop/rt-plugin-report.php#L58

The translation functions are using "plugin-report" too, for example seen here:
https://github.com/roytanck/rt-plugin-report/blob/develop/rt-plugin-report.php#L108

So I think you should change "rt-plugin-report" to "plugin-report" in line 58.

But the text domain header is not needed anymore after WP 4.6:
https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#text-domains

After WP 4.6 the loading of the language files is easier BTW too:
https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#loading-text-domain

Then you can use the language packs from translate.wordpress.org if your plugin is in the directory (which is your plan, if I remember your tweet correctly).

I don't know what you want to support finally, so I don't make any PR and leave the decision to you.

The important thing is: If you submit the plugin to the directory, the slug must match with the text domain ("plugin-report").

**Comment by roytanck** [comment]
Thanks for catching this. I've fixed the slug in line 58, "plugin-report" is the domain I'm going with.

I like having the text domain in the header, if only for myself while developing. The call to load_plugin_textdomain is still needed in situations where the plugin can't make external connections, I think. This particular plugin would be pretty useless in such an environment, but at least the error messages will be in the correct language.

**Comment by Zodiac1978** [comment]
> I like having the text domain in the header, if only for myself while developing. 

This is not necessary if you code for WP 4.6 or above, as this now defaults to the plugin slug already by default. See my link from above:
https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#text-domains (especially the blue box!)

> The call to load_plugin_textdomain is still needed in situations where the plugin can't make external connections, I think. 

Not exactly. If you are using translate.wordpress.org and your plugin is translated 95% (or more) a language pack is generated. This is saved in /wp-content/languages/ and after that no external connection is necessary.

If you are loading the translation like it is in your case now, then it will try to load the files from the plugin itself, but there is no languages directory with any translations, so there is no reason to use this way (older plugins or plugins with many strings had uncompleted version loaded this way, because language packs weren't there in the beginning and are generate at 95%, so with this approach there at least some strings translated). 

In this case here I would recommend to omit this completely and require WP 4.6 or use the function call without parameters and require a lower version, like explained in the second link:
https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#loading-text-domain

**Comment by roytanck** [comment]
> Not exactly. If you are using translate.wordpress.org and your plugin is translated 95% (or more) a language pack is generated. This is saved in /wp-content/languages/ and after that no external connection is necessary.

That initial connection is going to be a problem in some cases*, but in those same cases this plugin is not going to work anyway. I'll remove the call to load_plugin_textdomain.

* I do a lot of government work with WP, and often wp.org is completely blocked.

**Comment by roytanck** [comment]
Fixed in commit https://github.com/roytanck/rt-plugin-report/commit/0a7eda0ce699771f188db108e648c71545b6dcaf .
