### ISSUE TITLE
Multisite feature request: add a list of subsites where plugin is enabled

### ISSUE THREAD

**Issue by joostdekeijzer** [roytanck/rt-plugin-report#52]
Hi Roy,

Just discovered this plugin and I love it! I use it to find if plugins are used in sub-sites in mulitisite environments. So I know if I can safely remove a plugin.

It would be really helpful if, besides the "2/12" activated I could get a list (use a hover?) of the subsites that the plugin is enabled in. Now I need to go through all 12 subsites to see if it's enabled...

Let me know what you think, I might try a PR

Thanks!

**Comment by roytanck** [comment]
Hi @joostdekeijzer . Thanks for the suggestion. Another plugin of mine actually has this feature. If you're a multisite admin, you might find it insteresting: https://wordpress.org/plugins/network-admin-assistant/

**Comment by joostdekeijzer** [comment]
Ah, but that is perfect too 😃
