### ISSUE TITLE
Repository not correctly shown for WP <5.8

### ISSUE THREAD

**Issue by Zodiac1978** [roytanck/rt-plugin-report#53]
I've experienced something strange on a WP 5.5.9 multisite.

The column "Repository" shows for every plugin "No data available".

This is because the used header info is first introduced in WP 5.8, I think:
https://make.wordpress.org/core/2021/06/29/introducing-update-uri-plugin-header-in-wordpress-5-8/

Relevant code:
https://github.com/roytanck/rt-plugin-report/blob/fdfe98dcb315294f58a3cfe333af1cf7385144c1/rt-plugin-report.php#L438-L469

Not sure if this is clear for every user. I needed some minutes to understand why this is failing ...

**Comment by roytanck** [comment]
While "no data available" is technically true, there are a couple of ways I think we could handle this.

1. Bump the minimum required WP version for the plugin to 5.8.
2. Use a different message on WP < 5.8.
3. Hide the column on WP < 5.8.

While option 3 is probably the most elegant solution, it's also the most work. The number of columns is currently fixed, and making it flexible would require us to make the colspan on error rows flexible too.

**Comment by Zodiac1978** [comment]
Bumping the required version would solve the issue but the plugin is such a helpful tool to find the compatibility for all the plugins before a core upgrade, so I wouldn't recommend this way.

Using a different message should be easy to implement with a version compare on the core version.

If 3 has problems due to the table markup, let's go with 2 and just change the text.

How about "Repository data available in WP 5.8 or higher" (a little bit long ...), maybe just "Available in WP 5.8+"?

**Comment by roytanck** [comment]
Agreed. If you have time, could you create a PR for this? If not, please assign to me.

**Comment by Zodiac1978** [comment]
I can create a PR. (And I cannot assign you, because I am just a contributor ...) 😉

Any opinions about the text?
