### ISSUE TITLE
Transient key length may cause issues for plugins with slugs exceeding 22 chars

### ISSUE THREAD

**Issue by dannyvankooten** [roytanck/rt-plugin-report#8]
Because transients are stored as options, there is a maximum key length of 45 characters for transients with an expiration time. This is because the maximum option name length is 64 characters, where (the expiration time for) a transient gets the suffix `_transient_timeout_` (19 characters), leaving 45 characters for the transient name itself.

https://github.com/roytanck/rt-plugin-report/blob/f3c2a6e1f1ff1ce4b76b722da68829daf7fc4de6/rt-plugin-report.php#L253

The plugin uses `rt_plugin_report_cache_` (23 characters) for the transient key prefix, leaving 22 characters for the plugin slug itself. While this should be sufficient for most, it fails on slugs like "google-analytics-dashboard-for-wp" (33 characters).

The effect of this is that the result is never cached for plugins with slugs exceeding 22 characters. 

Related Trac ticket: https://core.trac.wordpress.org/ticket/15058

**Comment by Zodiac1978** [comment]
Good catch!

**Comment by roytanck** [comment]
Since I can find no info on the maximum slug length in the WP plugin repo, I thing the best bet would be to use a shorter prefix, and a hash of the slug. That would give us a predictable transient key length.

**Comment by roytanck** [comment]
@dannyvankooten It appears that in a multisite install, using site transients, an even longer string gets prefixed: `_site_transient_timeout_` (24 chars). I see no issues on my test install, but I'll be aiming to keep the key under/at 64 chars nonetheless.
